routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::any('/logout', 'Auth\LoginController@logout')->name('logout');
Route::redirect('/home', '/index')->name('home');

Route::any('/exchange/from/{from}/to/{to}', 'ExchangeController@applyExchange')
    ->where('from', '[\w_]+')
    ->where('to', '[\w_]+')
    ->name('change-action');

Route::get('/exchange/{id}_{email}', 'ExchangeController@verifyExchange')
    ->where('id', '\d+')
    ->name('exchange-verify');

Route::any('/exchange/discard/{id}_{email}', 'ExchangeController@discardExchange')
    ->where('id', '\d+')
    ->name('exchange-discard');

app/Models/Exchange.php
<?php

namespace App\Models;

use App\Models\ExchangeTargets\BitcoinTarget;
use App\Models\ExchangeTargets\TargetModel;
use Backpack\CRUD\CrudTrait;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Log;

/**
 * Модель обменов.
 * Здесь хранится необходимая информация для проверки и отправки платежей.
 *
 * Class Exchange
 * @property int status статус обмена
 * @property string email почта пользователя
 * @property TargetModel from
 * @property TargetModel to
 * @package App\Models
 */
class Exchange extends Model {
    use CrudTrait;

    const CREATED = 1; // обмен создан
    const DONE = 2; // обмен завершён успешно
    const ERROR = 3; // обмен завершён с ошибкой
    const DISCARD_BY_USER = 4; // обмен отклонён пользователем
    const DISCARD_BY_ADMIN = 5; // обмен отклонён администрацией

    protected $fillable = [
        'email', 'status', 'profit',
        'from_type', 'from_id',
        'to_type', 'to_id',
    ];

    protected $rules = [
        'email' => 'required|email',
    ];

    protected $rulesMessages = [
        'email.*' => 'Введите ваш реальный почтовый адрес',
    ];

    public function scopeToBitcoin(Builder $query) {
        return $query->where('to_type', BitcoinTarget::class);
    }

    public function scopeFromBitcoin(Builder $query) {
        return $query->where('from_type', BitcoinTarget::class);
    }

    public function scopeAccepted(Builder $query) {
        return $query->where('status', self::DONE);
    }

    public function scopeErrored(Builder $query) {
        return $query->whereIn('status', [self::ERROR, self::DISCARD_BY_ADMIN, self::DISCARD_BY_USER]);
    }

    public function scopeDiscarded(Builder $query) {
        return $query->whereIn('status', [self::DISCARD_BY_ADMIN, self::DISCARD_BY_USER]);
    }

    public function from() {
        return $this->morphTo('from');
    }

    public function to() {
        return $this->morphTo('to');
    }

    /**
     * Возвращает ссылку на которую будет перенесён клиент после создания обмена.
     * @return mixed|string
     */
    public function getPayRedirectAttribute() {
        return $this->from->getRedirectUrl();
    }

    /**
     * Врзвращает ссылку на страницу с проверкой статуса обмена.
     * @return string
     */
    public function getVerifyExchangeUrlAttribute() {
        // дабы нельзя было посмотреть чужой
        return route('exchange-verify', [
            'id'    => $this->id,
            'email' => $this->email,
        ]);
    }

    public function getDisplyStatusAttribute() {
        switch ($this->status) {
            case self::CREATED:
                return 'Заявка создана. Ожидание оплаты пользователя.';
            case self::DONE:
                return 'Обмен совершён.';
            case self::ERROR:
                return 'Обмен завершён с ошибкой.';
            case self::DISCARD_BY_USER:
                return 'Обмен отклонён пользователем.';
            case self::DISCARD_BY_ADMIN:
                return 'Обмен отклонён администрацией.';
            default:
                return '~~NOT FOUND STATE ' . $this->status;
        }
    }

    /**
     * Проверяет, оплатил ли юзер.
     *
     * @param null $context дополнительные данные
     * @return bool true если мы проверили платёжь (если юзер перевёл деньги)
     */
    public function checkExchange($context = null) {
        try {
            return $this->from->checkExchange($context);
        } catch (Exception $e) {
            Log::error('Check fails ' . $this->id);
            return false;
        }
    }

    public function getReceiveCountAttribute() {
        return $this->from->receive_count;
    }

    public function getSendCountAttribute() {
        return $this->to->send_count;
    }

    /**
     * Завершаем обмен и переводим юзеру его деньги.
     *
     * @param null $context дополнительные данные
     * @return mixed
     */
    public function endExchange($context = null) {
        try {
            $this->to->endExchange($context);
            $this->status = self::DONE;
            $this->save();

            return $this;
        } catch (Exception $e) {

            abort(404);
            return null;
        }
    }

    public function getFailButton() {
        if ($this->status != self::CREATED) return '';

        return '<a href="' . backpack_url('exchange/' . $this->id . '/fail') . '" class="btn btn-xs btn-default"><i class="fa fa-times"></i> Закрыть обмен</a>';
    }
}

app/Models/ExchangeTargets/QiwiTarget.php
<?php

namespace App\Models\ExchangeTargets;

use App\Models\QiwiWallet;
use App\QiwiParser\Qiwi;
use App\QiwiParser\QiwiWalletManager;
use Cache;
use Carbon\Carbon;

class QiwiTarget extends TargetModel {

    protected $fillable = [
        'direction', 'user_qiwi_wallet', 'receive_qiwi_wallet',
        'send_count', 'receive_count',
    ];

    protected $rules = [
        'direction'           => 'required|string',
        'user_qiwi_wallet'    => 'nullable|regex:/\+?[78]\d{3}\d{7}/',
        'receive_qiwi_wallet' => 'nullable|numeric',
        'receive_count'       => 'nullable|numeric',
    ];

    protected $rulesMessages = [
        'user_qiwi_wallet.*' => 'Телефон заполнен не верно. (пример: +79261234567)',
        'receive_count.min'  => 'Слишком маленькая сумма (руб).',
        'send_count.max'     => 'Слишком большая сумма (руб).',
        'receive_count.*'    => 'Значение должно быть числом.',
    ];

    public function checkExchange($context = null) {
        $wallet = QiwiWallet::where('login', $this->receive_qiwi_wallet)->first();
        /** @var QiwiWalletManager $manager */
        $manager = $wallet->getManager();

        $from = substr($this->user_qiwi_wallet, 2);

        $qiwi_hist = Cache::remember('blockchain:qiwi:history-' . $wallet->id, 3, function () use ($manager) {
            return collect($manager->history($this->created_at, now())['data']);
        });

        $qiwi = $qiwi_hist->where('error', null)
            ->where('errorCode', 0)
            ->where('type', 'IN')
            ->where('status', 'SUCCESS')
            ->where('account', "+7$from")
            ->where('total.amount', $this->receive_count);

        return $qiwi->reduce(function ($carry, $item) {
            return $carry || Carbon::parse($item['date'])->greaterThan($this->created_at);
        }, false);
    }

    public function endExchange($context = null) {
        $sender = new Qiwi();
        $sender->massSend($this->send_count, $this->user_qiwi_wallet);
        return null;
    }


    /**
     * Возвращает подходящий киви кошелёк
     * @return string
     * @throws \Illuminate\Validation\ValidationException
     */
    public function getReceiveQiwiWalletAttribute() {
        if (!$this->getOriginal('receive_qiwi_wallet')) {
            $qiwi_manager = new Qiwi();
            $free_wallet = $qiwi_manager->freeWallet($this->from_count);
            if (!$free_wallet) return '~~NO_WALLET';
            $free = $free_wallet->login;
            $this->receive_qiwi_wallet = $free;
            $this->save();
        } else return $this->getOriginal('receive_qiwi_wallet');

        return $free;
    }

    public function getPayUrlAttribute() {
        $to = $this->exchange->to;
        $name = head(explode('-', kebab_case(class_basename($to->getMorphClass()))));
        return 'https://qiwi.com/payment/form/99?' . http_build_query([
                'currency'       => 643,
                'amountInteger'  => floor($this->receive_count),
                'amountFraction' => fmod($this->receive_count, 1) * 100,
                'extra'          => [
                    '\'account\'' => $this->receive_qiwi_wallet,
                    '\'comment\'' => 'Обмен с qiwi (' . $this->receive_count . ' RUB) на ' . $name . ' (' . $to->send_count . ') сервисом ' . config('app.name'),
                ],
            ]);
    }

    public function toHtml($content = '') {
        return parent::toHtml(view('admin.column.qiwi-target', ['target' => $this]));
    }

    protected function getRules(): array {
        $rules = $this->rules;

        if ($this->direction == 'to') {
            $max = QiwiWallet::valid()->sum('balance');

            $rules['user_qiwi_wallet'] = 'required|regex:/\+?[78]\d{3}\d{7}/';
            $rules['send_count'] = "required|numeric|max:$max";
        }

        if ($this->direction == 'from') {
            $min = config('settings.wallet.qiwi.min');

            $rules['user_qiwi_wallet'] = 'required|regex:/\+?[78]\d{3}\d{7}/';
            $rules['receive_count'] = "required|numeric|min:$min";
        }

        return $rules;
    }
}

resources/views/client/verify-exchange/base.blade.php
@extends('layout.user')

@section('content')
    <div id="exchange-section">
        <div class="container">
            <div class="row flex-column justify-content-center vh-100">
                <div class="col-0">
                    <div class="exchange-card">
                        <p>
                            <b>Время создания:</b> {{ $exchange->created_at }}
                        </p>
                        <p>
                            <b>Статус:</b> {{ $exchange->disply_status }}
                        </p>
                        <p class="font-weight-light">
                            Данная операция занимает от 5 до 90 минут. Платеж считается полученным при накоплении 2х
                            подтверждений со стороны Blockchain.
                        </p>
                        <div class="row no-gutters mt-3 mb-4">
                            <div class="col">
                                <button type="submit" onclick="window.location.reload()"
                                        class="btn btn-lg btn-block btn-secondary">Обновить статус
                                </button>
                            </div>
                            @if($exchange->status == \App\Models\Exchange::CREATED)
                                <div class="col-0">
                                    <button type="submit"
                                            onclick="window.location = '{{ route('exchange-discard', ['from' => $exchange->from, 'id' => $exchange->id, 'email' => $exchange->email]) }}'"
                                            class="btn btn-lg btn-block btn-danger ml-2">Отменить обмен
                                    </button>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('client.components.support')
@endsection

resources/views/client/verify-exchange/bitcoin-target.blade.php
@extends('layout.user')

@section('content')
    <div id="exchange-section">
        <div class="container">
            <div class="row flex-column justify-content-center vh-100">
                <div class="col-0">
                    <div class="exchange-card">
                        <h1>Как оплатить</h1>
                        <p>
                            <b>Переведите точную сумму</b>: {{ $exchange->from->receive_count }} BTC
                        </p>
                        <p>
                            <b>На кошелек</b>: {{ $exchange->from->creteReceiveWallet() }}
                        </p>
                        <p>
                            <b>Идентификатор обмена:</b> id{{ $exchange->id }}
                        </p>
                        <p>
                            <b>Время создания:</b> {{ $exchange->created_at }}
                        </p>
                        <p>
                            <b>Статус:</b> {{ $exchange->disply_status }}
                        </p>
                        <p class="text-warning font-weight-bold">
                            Пожалуйста, будьте внимательны!<br>
                            Все поля должны быть заполнены в точном соответствии с инструкцией. В противном случае,
                            платеж может не пройти.
                        </p>
                        <p class="font-weight-light">
                            Данная операция занимает от 5 до 90 минут. Платеж считается полученным при накоплении 2х
                            подтверждений со стороны Blockchain.
                        </p>
                        <div class="row no-gutters mt-3 mb-4">
                            <div class="col">
                                <button type="submit" onclick="window.location.reload()"
                                        class="btn btn-lg btn-block btn-secondary">Обновить статус
                                </button>
                            </div>
                            @if($exchange->status == \App\Models\Exchange::CREATED)
                                <div class="col-0">
                                    <button type="submit"
                                            onclick="window.location = '{{ route('exchange-discard', ['from' => $exchange->from, 'id' => $exchange->id, 'email' => $exchange->email]) }}'"
                                            class="btn btn-lg btn-block btn-danger ml-2">Отменить обмен
                                    </button>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('client.components.support')
@endsection

resources/views/client/verify-exchange/qiwi-target.blade.php
@extends('layout.user')

@section('content')
    <div id="exchange-section">
        <div class="container">
            <div class="row flex-column justify-content-center vh-100">
                <div class="col-0">
                    <div class="exchange-card">
                        <h1>Как оплатить</h1>
                        <p>
                            <b>Переведите точную сумму</b>: {{ $exchange->from->receive_count }} RUB
                        </p>
                        <p>
                            <b>На номер qiwi кошелька</b>: {{ $exchange->from->receive_qiwi_wallet }}
                        </p>
                        <p>
                            <b>Обязательно укажите коментарий</b>:
                            Обмен с qiwi ({{ $exchange->from->receive_count }} RUB)
                            на bitcoin ({{ $exchange->to->send_count }} BTC)
                            сервисом {{ config('app.name') }}
                        </p>
                        <p>
                            <b>Идентификатор обмена:</b> id{{ $exchange->id }}
                        </p>
                        <p>
                            <b>Время создания:</b> {{ $exchange->created_at }}
                        </p>
                        <p>
                            <b>Статус:</b> {{ $exchange->disply_status }}
                        </p>
                        <p class="text-warning font-weight-bold">
                            Пожалуйста, будьте внимательны!<br>
                            Все поля должны быть заполнены в точном соответствии с инструкцией. В противном случае,
                            платеж может не пройти.
                        </p>
                        <p class="font-weight-light">
                            Данная операция занимает от 5 до 90 минут. Платеж считается полученным при накоплении 2х
                            подтверждений со стороны Blockchain.
                        </p>
                        <div class="row no-gutters mt-3 mb-4">
                            <div class="col">
                                <button type="submit" onclick="window.location.reload()"
                                        class="btn btn-lg btn-block btn-secondary">Обновить статус
                                </button>
                            </div>
                            @if($exchange->status == \App\Models\Exchange::CREATED)
                                <div class="col-0 pl-2">
                                    <a href="{{ $exchange->from->pay_url }}"
                                       class="btn btn-lg btn-block btn-primary">
                                        Перейти на форму оплаты
                                    </a>
                                </div>
                                <div class="col-0 pl-2">
                                    <button type="submit"
                                            onclick="window.location = '{{ route('exchange-discard', ['from' => $exchange->from, 'id' => $exchange->id, 'email' => $exchange->email]) }}'"
                                            class="btn btn-lg btn-block btn-danger">Отменить обмен
                                    </button>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('client.components.support')
@endsection